systematicsAndShapes = {
 "yields": { # This always needs to be defined
           "name": "yields",
           "type": "yieldsWithShapes",
           "file": "[ROOTFILE]_[CHANNEL].root",
           "match": "[VAR]_[CHANNEL]_$PROCESS",
           "extendedABCD": {"SR": "_SR", "B1": "_B1", "B2":"_B2", "C1":"_C1", "C2":"_C2", "D1":"_D1", "D2":"_D2","E1":"_E1", "E2":"_E2"}
 },
 "TrigSF"  : {
            "name": "TrigSF",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "ElSF"  : {
            "name": "ElSF",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "MuSF"  : {
            "name": "MuSF",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "PU"  : {
            "name": "PU",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
            "flatten": [["E2_bin1","E1_bin1",'B2_bin1', 'B2_bin2', 'B2_bin3', 'B2_bin4', 'B2_bin5', 'B2_bin6', 'B2_bin7', 'B2_bin8'],["D2_bin1","D1_bin1",'B1_bin1', 'B1_bin2', 'B1_bin3', 'B1_bin4', 'B1_bin5', 'B1_bin6', 'B1_bin7', 'B1_bin8'],["C1_bin1","C2_bin1",'SR_bin1', 'SR_bin2', 'SR_bin3', 'SR_bin4', 'SR_bin5', 'SR_bin6', 'SR_bin7', 'SR_bin8']],            
 },
 "L1"  : {
            "name": "L1",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "ISR"  : {
            "name": "ISR",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
            "flatten": [["E2_bin1","E1_bin1",'B2_bin1', 'B2_bin2', 'B2_bin3', 'B2_bin4', 'B2_bin5', 'B2_bin6', 'B2_bin7', 'B2_bin8'],["D2_bin1","D1_bin1",'B1_bin1', 'B1_bin2', 'B1_bin3', 'B1_bin4', 'B1_bin5', 'B1_bin6', 'B1_bin7', 'B1_bin8'],["C1_bin1","C2_bin1",'SR_bin1', 'SR_bin2', 'SR_bin3', 'SR_bin4', 'SR_bin5', 'SR_bin6', 'SR_bin7', 'SR_bin8']],
 },
 "FSR"  : {
            "name": "FSR",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
            "flatten": [["E2_bin1","E1_bin1",'B2_bin1', 'B2_bin2', 'B2_bin3', 'B2_bin4', 'B2_bin5', 'B2_bin6', 'B2_bin7', 'B2_bin8'],["D2_bin1","D1_bin1",'B1_bin1', 'B1_bin2', 'B1_bin3', 'B1_bin4', 'B1_bin5', 'B1_bin6', 'B1_bin7', 'B1_bin8'],["C1_bin1","C2_bin1",'SR_bin1', 'SR_bin2', 'SR_bin3', 'SR_bin4', 'SR_bin5', 'SR_bin6', 'SR_bin7', 'SR_bin8']],
 },
 "LFCorr"  : {
            "name": "LFCorr",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "LFUnCorr"  : {
            "name": "LFUnCorr",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},

 },
 "HFCorr"  : {
            "name": "HFCorr",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "HFUnCorr"  : {
            "name": "HFUnCorr",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
 },
 "Track"  : {
            "name": "Track",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
            "flatten": [['SR_bin1', 'B1_bin1', 'B2_bin1'], ['SR_bin2', 'B1_bin2', 'B2_bin2'], ['SR_bin3', 'B1_bin3', 'B2_bin3'], ['SR_bin4', 'B1_bin4', 'B2_bin4'], ['SR_bin5', 'B1_bin5', 'B2_bin5'], ['SR_bin6', 'B1_bin6', 'B2_bin6'], ['SR_bin7', 'B1_bin7', 'B2_bin7'], ['SR_bin8', 'B1_bin8', 'B2_bin8'], ['E1_bin1','D1_bin1','C1_bin1'], ['E2_bin1','D2_bin1','C2_bin1']],
 },
 "JEC"  : {
            "name": "JEC",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",     
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
            "flatten": [["E2_bin1","E1_bin1",'B2_bin1', 'B2_bin2', 'B2_bin3', 'B2_bin4', 'B2_bin5', 'B2_bin6', 'B2_bin7', 'B2_bin8'],["D2_bin1","D1_bin1",'B1_bin1', 'B1_bin2', 'B1_bin3', 'B1_bin4', 'B1_bin5', 'B1_bin6', 'B1_bin7', 'B1_bin8'],["C1_bin1","C2_bin1",'SR_bin1', 'SR_bin2', 'SR_bin3', 'SR_bin4', 'SR_bin5', 'SR_bin6', 'SR_bin7', 'SR_bin8']],
 },
 "JER"  : {
            "name": "JER",
            "type": "shape",
            "processes": ["SUEP.*"],
            "match": "$PROCESS_$SYSTEMATIC",
            "up"  : "Up",
            "down": "Dn",
            "corrs": {"RunII":["RunII"]},
            "flatten": [["E2_bin1","E1_bin1",'B2_bin1', 'B2_bin2', 'B2_bin3', 'B2_bin4', 'B2_bin5', 'B2_bin6', 'B2_bin7', 'B2_bin8'],["D2_bin1","D1_bin1",'B1_bin1', 'B1_bin2', 'B1_bin3', 'B1_bin4', 'B1_bin5', 'B1_bin6', 'B1_bin7', 'B1_bin8'],["C1_bin1","C2_bin1",'SR_bin1', 'SR_bin2', 'SR_bin3', 'SR_bin4', 'SR_bin5', 'SR_bin6', 'SR_bin7', 'SR_bin8']],
 },
 "lumi"  : {
            "name": "lumi",
            "type": "lnN",
            "processes": ["SUEP.*"],
            "size": 1.016,
            "corrs": {"RunII":["RunII"]},
 },
 "closure" : {
            "name": "closure",
            "type": "lnN",
            "processes": [".*bkg.*",".*background.*"],
            "size": 1.2,
            "corrs": {"RunII":["RunII"]},
            "perbin": True,
            "onlychannel": "SR",
 },
}
